lib/optimizely.rb
lib/optimizely/event_builder.rb
lib/optimizely/event_dispatcher.rb
spec/event_builder_spec.rb
spec/event_dispatcher_spec.rb
spec/project_spec.rb

- Adds method and URL properties to `Event`
- Adds method argument to `EventDispatcher.dispatch_event`
- Renames `EventBuilder` to `EventBuilderV1`
- Removes abstract `BaseEventBuilder` class (https://github.com/bbatsov/ruby-style-guide#duck-typing)
- Locks down a few unnecessary `attr_accessors` to `attr_readers`
- Fixes broken tests
@aliabbasrizvi @delikat @haleybash-optimizely @mikeng13 @alda-optimizely @wangjoshuah @jophde @jsm

Add method and URL to Event, add method to EventDispatcher

---

optimizely-sdk.gemspec

It generally helps to be optimistic about patch version requirements on
runtime dependencies used in a gem. This should help reduce version conflicts when
using this gem.

Relax patch version requirements on runtime dependencies

---

lib/optimizely/bucketer.rb
lib/optimizely/decision_service.rb
spec/bucketing_spec.rb
spec/decision_service_spec.rb
spec/project_config_spec.rb
spec/spec_params.rb

Features bucketing

---

lib/optimizely.rb
lib/optimizely/decision_service.rb
lib/optimizely/project_config.rb
spec/decision_service_spec.rb
spec/project_config_spec.rb
spec/project_spec.rb

Add feature flag accessor API

---

lib/optimizely/bucketer.rb
lib/optimizely/decision_service.rb
lib/optimizely/event_builder.rb
spec/bucketing_spec.rb
spec/decision_service_spec.rb
spec/event_builder_spec.rb
spec/project_spec.rb
spec/spec_params.rb

🖊  Please note that since data file in Ruby SDK is different from PHP-SDK, the resulting experiment/variation values and the flow of resulting log statements due to bucketing may differ in the unit tests.

Feature - Bucketing IDs

---

lib/optimizely/audience.rb
lib/optimizely/decision_service.rb
lib/optimizely/project_config.rb
spec/decision_service_spec.rb
spec/project_config_spec.rb

✏️ Bucketer.bucket call arguments fixed and unit tests cases updated to ensure right number of params are passed
✏️ Revision of logic in Decision Service getVariationForFeatureExperiment 
✏️ Refactoring of new Decision Service logic

Fix Rollout Bucketer.bucket call & Decision Service logic

---

lib/optimizely.rb
spec/project_spec.rb

Updates following optimizely methods to fix empty user_id issue:
:pen:  get_variation
:pen: track
:pen:  get_feature_variable_for_type

Implements missing validations

---

lib/optimizely/project_config.rb

We just integrated this gem into our Rails project at work, and have begun seeing the following warning when booting the app (via docker) or running the suite:
`/usr/local/bundle/gems/optimizely-sdk-2.0.1/lib/optimizely/project_config.rb:90: warning: string literal in condition`
Our suspicion is that the ruby interpreter wasn't properly parsing the lack of parens on the `.key?` method call in: `@anonymize_ip = config.key? 'anonymizeIP' ? config['anonymizeIP'] : false` 
Lemme know what you think.  As I said, we just started using this gem but it's been working great so far - thanks for the work!

Use parens to prevent string literal in condition

---

lib/optimizely.rb
spec/project_spec.rb

:wave: This recently caused a bit of noise for us 😅 after upgrading our SDK. It looks like `Optimizely::Project` is intended to work without a custom logger, but tracking events with tags started raising `NoMethodError`:
```
$GEM_HOME/optimizely-sdk-2.1.0/lib/optimizely/helpers/event_tag_utils.rb:52:in `get_revenue_value': undefined method `log' for nil:NilClass (NoMethodError)
from $GEM_HOME/optimizely-sdk-2.1.0/lib/optimizely/event_builder.rb:220:in `block in get_conversion_params'
from $GEM_HOME/optimizely-sdk-2.1.0/lib/optimizely/event_builder.rb:202:in `each'
from $GEM_HOME/optimizely-sdk-2.1.0/lib/optimizely/event_builder.rb:202:in `get_conversion_params'
from $GEM_HOME/optimizely-sdk-2.1.0/lib/optimizely/event_builder.rb:155:in `create_conversion_event'
from …
```

EventBuilder uses the same logger as Project

---

lib/optimizely/bucketer.rb
lib/optimizely/helpers/validator.rb
lib/optimizely/project_config.rb
optimizely-sdk.gemspec

**Summary**
- In PR https://github.com/optimizely/ruby-sdk/pull/133 Rubocop's latest version 0.60.0 was installed, due to which later PRs were getting failed with lint errors.
- Configured rubocop with latest version ` 0.60.0`.
- Fixed lint errors.

Fix: Lint errors after rubocop update.

---

.rubocop.yml
lib/optimizely/project_config.rb
spec/project_config_spec.rb

- Forced variation key passed as an empty String will be invalid argument.
- Updated inputs validation for set_forced_variation.
- Updated unit tests for empty string variation key.

fix(set_forced_variation): Treats empty variation key as invalid and does not reset forced variation.

---

lib/optimizely.rb
lib/optimizely/helpers/validator.rb
lib/optimizely/project_config.rb
spec/project_config_spec.rb
spec/project_spec.rb

1. Aattributes validation in APIs(is_feature_enabled, get_enabled_features and get_feature_variables).
2. Allow empty user id.

refact(API): Adds missing input validations in all API methods and validates empty user Id.

---

lib/optimizely/helpers/validator.rb
spec/custom_attribute_condition_evaluator_spec.rb
spec/validator_helper_spec.rb

Summary
-------
Don't target NAN, INF or -INF
Don't target Values > 2^53. 
Modified attribute_valid? to check if the number is finite. 
Test plan
---------
Issues
------
OASIS-3654

feat(attribute_value): Don't target NAN, INF, -INF and > 2^53

---

lib/optimizely/audience.rb
spec/audience_spec.rb
spec/project_config_spec.rb
spec/project_spec.rb
spec/spec_params.rb

Summary
-------
This adds support for audience combinations on experiments. If `experiment['audienceConditions']` is present, it will be used as a condition tree where the leaf conditions are audience Ids.
- Experiments can now be evaluated on behalf of either complex audienceConditions or simple audienceIds
- Audience conditions can either be a string defining array of conditions or simply a string of audience id which is then converted to an OR condition.
- Priority will be given to audienceConditions if both audienceIds and audienceConditions are present.
Test plan
---------
- test_optimizely - Added unit tests for APIs that pass/fail using various complex audiences with different match types. 
- Ran complex audiences test cases in compatibility test suite.
Issues
------

feat(audiences): Audience combinations

---

.travis.yml
optimizely-sdk.gemspec

- Added new ruby version (2.6.0) support.
- Updated rubocop version to 0.62 as it failed: https://github.com/rubocop-hq/rubocop/pull/6470

ci: Adding support for testing on Ruby 2.6.0

---

lib/optimizely.rb
lib/optimizely/event_builder.rb
lib/optimizely/project_config.rb
spec/event_builder_spec.rb
spec/project_config_spec.rb
spec/project_spec.rb

- Impression/Conversion events now have a 'enrich_decisions' boolean property set to true.
- conversion events now do not have the decision property in visitor snapshots. 
- Conversion event is now sent solely if the event key corresponds to a valid event in the data file.
- Unit Tests updated
- Tested Compat Suite Tests for EET locally. 
- OASIS-4031

feat(track): Introducing easier event tracking

---

.travis.yml

This uses the script from travisci-tools repo to trigger compat suite. 
OASIS-4389

ci: use script from travisci-tools repo to trigger tests

---

lib/optimizely.rb
lib/optimizely/helpers/constants.rb
lib/optimizely/notification_center.rb
spec/project_spec.rb

Summary
-------
Implemented onDecisionListener in following APIs:
- activate
- get_variation
Test plan
---------
Unit tests for OnDecisionListener
Issues
------
- OASIS-4233

feat(DecisionListener): Adds experiment decision listener.

---

lib/optimizely.rb
spec/project_spec.rb

- Feature variable APIs now return default variable value when featureEnabled property is false.
- Updated rubocop configuration to fix Metrics/BlockNesting error.
- Added unit tests.

feat(api): Feature variable APIs return default variable value when featureEnabled property is false.

---

lib/optimizely.rb
lib/optimizely/decision_service.rb
lib/optimizely/helpers/constants.rb
lib/optimizely/project_config.rb
spec/decision_service_spec.rb
spec/project_config_spec.rb
spec/project_spec.rb
spec/spec_params.rb

- Incorporated new decision notification listener changes.
- Added unit tests for type `feature-test` and project config method.
- Updated unit tests.

feat(decision-listener): Incorporated new decision notification listener changes.

---

lib/optimizely/project_config.rb
spec/project_config_spec.rb
spec/spec_params.rb

- Updated rollout experiment mapping.
- Added rollout experiment with different ID and key
- Modified existing mapping tests and added new one.
- OASIS-4722

Fix(is_feature_enabled):  Added rollout experiment key map for onboarding datafile

---

lib/optimizely.rb
lib/optimizely/bucketer.rb
lib/optimizely/decision_service.rb
lib/optimizely/event_builder.rb
spec/bucketing_spec.rb
spec/decision_service_spec.rb
spec/event_builder_spec.rb
spec/notification_center_spec.rb

Summary
-------
- Moved out ProjectConfig from `Bucketer`, `DecisionService` and `EventBuilder`. Project Config will now only be passed on method calls. 
Test plan
---------
Unit tests and compatibility suite tests continue to pass.

feat(datafile-management) Refactoring and passing ProjectConfig from Optimizely.

---

lib/optimizely.rb
lib/optimizely/bucketer.rb
lib/optimizely/decision_service.rb
lib/optimizely/event_builder.rb
spec/bucketing_spec.rb
spec/decision_service_spec.rb
spec/event_builder_spec.rb
spec/notification_center_spec.rb

Summary
-------
- Moved out ProjectConfig from `Bucketer`, `DecisionService` and `EventBuilder`. Project Config will now only be passed on method calls. 
Test plan
---------
Unit tests and compatibility suite tests continue to pass.

Refactoring and passing ProjectConfig from Optimizely.

---

.rubocop_todo.yml
lib/optimizely.rb
lib/optimizely/audience.rb
lib/optimizely/bucketer.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/decision_service.rb
lib/optimizely/project_config.rb
spec/audience_spec.rb
spec/bucketing_spec.rb
spec/config/datafile_project_config_spec.rb
spec/config_manager/static_project_config_manager_spec.rb
spec/decision_service_spec.rb
spec/event_builder_spec.rb
spec/notification_center_spec.rb
spec/project_spec.rb

- Implemented ProjectConfig interface and created DatafileProjectConfig.
- Removed logger from config object; Passed separately in `user_in_experiment?`  method.
- Updated related unit tests

(feat): Implements ProjectConfig interface and creates DatafileProjectConfig.

---

optimizely-sdk.gemspec
spec/custom_attribute_condition_evaluator_spec.rb

- Rubocop 0.73 has been released; https://github.com/rubocop-hq/rubocop/releases
- Travis builds are getting failed due to this new release; https://travis-ci.org/optimizely/ruby-sdk/jobs/559878094
- Used latest version and resolved lint errors.

Fix: Rubocop latest version issues

---

.rubocop_todo.yml
lib/optimizely/event/entity/conversion_event.rb
lib/optimizely/event/entity/decision.rb
lib/optimizely/event/entity/event_batch.rb
lib/optimizely/event/entity/event_context.rb
lib/optimizely/event/entity/impression_event.rb
lib/optimizely/event/entity/snapshot.rb
lib/optimizely/event/entity/snapshot_event.rb
lib/optimizely/event/entity/user_event.rb
lib/optimizely/event/entity/visitor.rb
lib/optimizely/event/entity/visitor_attribute.rb
spec/event/event_entities_spec.rb

- Data models to represent Impression/Conversion event on client/server side.
- Unit tests to verify after serialization datamodel is converted into expected server payload
Impression Event
Conversion Event

feat(epmodel): Event Processor datamodel

---

README.md
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/helpers/constants.rb
spec/config_manager/http_project_config_manager_spec.rb

- Validates upper limit of polling interval & blocking timeout.
- Adds relative log messages
- Adds/Updates unit tests

fix(config-manager): Fixes polling interval and blocking timeout issues

---

lib/optimizely.rb
lib/optimizely/helpers/validator.rb
spec/project_spec.rb

- Implement `get_feature_variable` method in `optimizely.rb` to return value of variable with any type
- Changed `inputs_valid?` function in `validator.rb` to allow for `nil` variable type
- Create new unit tests in `project_spec.rb` to ensure functionality of `get_feature_variable`
Ruby is a dynamically-typed language, like [JavaScript](https://github.com/optimizely/javascript-sdk/pull/298), so it suffices to have a single method return the value of a feature variable rather than have a separate method for each possible feature variable type.
- Create unit tests in `project_spec.rb`
- Enable gherkin integration tests for Ruby in FSC suite and python-testapp
- Fulfills one of the [SDK convenience APIs](https://docs.google.com/document/d/1MCsMioa4TNImryaDdOJJsZwL9j5zFvFIXODArHF3ORs/edit#) …

Implement get_feature_variable and create unit tests

---

CHANGELOG.md

- Add `get_feature_variable` to the [Unreleased] header of Changelog
-
- References [#190](https://github.com/optimizely/ruby-sdk/pull/190)

chore(api): update Changelog with get_feature_variable method

---

.rubocop.yml
.rubocop_todo.yml
lib/optimizely/event/batch_event_processor.rb
lib/optimizely/event/event_factory.rb
lib/optimizely/event/event_processor.rb
lib/optimizely/helpers/date_time_utils.rb
spec/event/batch_event_processor_spec.rb

- Introduces an EventProcessor interface.
- Introduces a BatchEventProcessor
- Excluded `batch_event_processor.rb` from rubocop's Metrics/ParameterLists rule.
Buffering events within a queue before dispatching is an optimization that should prevent SDK implementations from exhausting resources while increasing throughput. This implementation relies on a `EventQueue` to buffer events received from one-to-many producers. A single consumer thread continuously polls from this queue to build a batch before emitting the batched `LogEvent`.
- Added unit tests

feat(eventProcessor): Add EventProcessor and BatchEventProcessor 

---

lib/optimizely.rb
lib/optimizely/event/batch_event_processor.rb
lib/optimizely/event/forwarding_event_processor.rb
lib/optimizely/notification_center.rb
spec/event/batch_event_processor_spec.rb
spec/event/forwarding_event_processor_spec.rb
spec/notification_center_spec.rb
spec/project_spec.rb

-  Introduced `LogEvent` notification in `notification_center.rb`.
- Integrated it in `batch_event_dispatcher.rb` and `forwarding_event_processor.rb`.
- Added `notification_count` in `notification_center.rb` and integrated into `Optimizely` for `notification types` _ACTIVATE_  and  _TRACK_.
- Added unit tests for `LogEvent` in `notification_center_spec.rb`, `batch_event_dispatcher_spec.rb` and `forwarding_event_processor_spec.rb`.
- Updated `Optimizely's` unit tests for `LogEvent` and `notification_count`.

feat(notification-center): Added LogEvent notification and integration.  

---

optimizely-sdk.gemspec

Per the rubygems guidelines, license files should be included in the
packaged gem. https://guides.rubygems.org/specification-reference/#license=
> The full text of the license should be inside of the gem (at the top level) when you build it.
closes #206

Include LICENSE file in built gem

---

lib/optimizely.rb
lib/optimizely/event/batch_event_processor.rb
lib/optimizely/event_dispatcher.rb
lib/optimizely/exceptions.rb
spec/event_dispatcher_spec.rb

- Allows Event Dispatcher to receive an optional logger and error handler
- Logs and calls Error Handler for Timeout or any other error raised. 
- Logs and calls Error Handler if response results into 4xx or 5xx status code. 
- Added new unit tests.
- OASIS-5687

feat: Log and Handle Error for Event Dispatcher response

---

lib/optimizely/event/batch_event_processor.rb
lib/optimizely/event_dispatcher.rb
spec/event/batch_event_processor_spec.rb
spec/event_dispatcher_spec.rb

- The loop ends up running too often and not paying attention to flush interval.
- Needs unit tests
- Batch event processor ends up in a tight always running loop when there are no events.

(fix): fix loop on batch event processor

---

.rubocop.yml
.travis.yml
lib/optimizely/event/batch_event_processor.rb
spec/event/batch_event_processor_spec.rb
spec/project_spec.rb

- Use a mutex so wait for a timeout since pop on SizedQueue does not support timeout.
- Empty the queue before going to mutex wait.
- Signal on process, flush, and stop.
- Add more debugging.
- Adjusted some unit tests.

(fix): refactor batch_processor to start on first process and use mutex to wait till deadline if nothing in the queue

---

.rubocop_todo.yml
lib/optimizely.rb
lib/optimizely/optimizely_config.rb
spec/optimizely_config_spec.rb

Added a `get_optimizely_config` API which returns static experiments and features data.
1. Manually tested thoroughly
2. Added Unit tests
3. Full Stack Integration tests passed

feat: get_optimizely_config API to get static experiments and features data

---

lib/optimizely.rb
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/config_manager/static_project_config_manager.rb
spec/config_manager/http_project_config_manager_spec.rb

Updated the `OptimizelyConfig` implementation to always return cached object. `OptimizelyConfig` object will only be updated when new `ProjectConfig` is received.
Added Unit Tests

feat: Added caching for optimizelyConfig object

---

CHANGELOG.md
lib/optimizely/version.rb

chore: prepare for release 3.4.0

---

.travis.yml
CHANGELOG.md
README.md

- Adds spellchecker to *.md
This is what it looks like when it finds a spelling error (aborts build):
https://travis-ci.org/optimizely/ruby-sdk/jobs/647067279

add spell check to markdown files

---

.travis.yml

this fixes a bug in the previous commit where the same input .spelling file was being used (locked to a particular commit SHA). what was intended was to keep using the latest version so that the .spelling file can be enhanced and it would be automatically picked up.

ci(mdspell): use latest version of .spelling

---

lib/optimizely/config_manager/async_scheduler.rb
spec/config_manager/async_scheduler_spec.rb

Async scheduler logs errors but does not pass it to an error handler. This does not allow this error to be reported in client's error reporting services. This PR sends these errors to the error_handler as well. 
Unit tests should pass
- OASIS-6306
https://github.com/optimizely/ruby-sdk/issues/205

handle error with error handler in async scheduler

---

spec/project_spec.rb

Some of the unit tests in project_spec make real http call to cdn.optimizely.com to test config manager. We mock them to avoid real http connections. 
All unit tests should continue to pass.

refact: avoid real http calls in unit tests

---

lib/optimizely.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/helpers/constants.rb
lib/optimizely/helpers/variable_type.rb
spec/config/datafile_project_config_spec.rb
spec/optimizely_config_spec.rb
spec/project_spec.rb
spec/spec_params.rb

Added new getFeatureVariableJson and getAllFeatureVariables Apis
Added Unit tests

feat: Added new getFeatureVariableJson and getAllFeatureVariables Apis

---

lib/optimizely/config/datafile_project_config.rb
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/exceptions.rb
spec/config_manager/http_project_config_manager_spec.rb
spec/project_spec.rb

Some of the errors being throw without the required msg argument to initialize that error type. Expecting handle_error method inside unit tests doesn't initialize the error instance. This PR modifies the raise error assertion inside unit tests and fixes where required. 
Also removes an unused error type. 
All tests continue to pass.

fix: errors being raised without required args

---

.gitignore
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/event_dispatcher.rb
lib/optimizely/helpers/http_utils.rb
lib/optimizely/helpers/network_utils.rb
optimizely-sdk.gemspec
spec/config_manager/http_project_config_manager_spec.rb
spec/event_dispatcher_spec.rb

A request was made to minimize library dependencies from the SDK. HTTParty was being used at a minimal level only for fetching datafile and dispatching events. This PR replaces HTTParty by core ruby net/http package
All tests continue to pass. 
https://github.com/optimizely/ruby-sdk/issues/211
OASIS-6453

refact: Replace httparty in favor of core net/http package

---

lib/optimizely/audience.rb
spec/audience_spec.rb

Modifying log level for single audience evaluation from INFO to DEBUG to reduce noise in logs. Now, only combined audience evaluation is logged at INFO level.
All checks pass.
- OASIS-6521

 fix(log-level) change single audience result to debug 

---

.rubocop_todo.yml
CHANGELOG.md
README.md
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/helpers/constants.rb
spec/config_manager/http_project_config_manager_spec.rb

Added support for Authenticated Datafiles
Added new unit tests

feat: Added support for Authenticated Datafiles

---

lib/optimizely/config_manager/http_project_config_manager.rb
spec/config_manager/http_project_config_manager_spec.rb

Added more debug logs to datafile manager to make debugging easy.
All Existing unit and FSC tests should pass

refactor: Added more logs to datafile manager

---

.rubocop_todo.yml
.travis.yml
README.md
lib/optimizely/config/proxy_config.rb
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/event_dispatcher.rb
lib/optimizely/helpers/http_utils.rb
spec/config/proxy_config_spec.rb
spec/config_manager/http_project_config_manager_spec.rb
spec/event_dispatcher_spec.rb
spec/helpers/http_utils_spec.rb

This branch is a copy of https://github.com/rloomba/ruby-sdk/tree/rloomba/add-proxy-config.  I simply moved it into a branch off of master from a fork to go through proper testing.
* add ability to use http proxy when making web requests
* fix: linting
* ignore spellcheck
* headers and missing test
* update to use master mdspell
Co-authored-by: Ryan Loomba <ryan@loomba.io>
Co-authored-by: Owais Akbani <owais.akbani92@gmail.com>
- Allow proxy to be passed into http config manager.
- "THING-1234" or "Fixes #123"

Rloomba/add proxy config (#262)

---

CHANGELOG.md
lib/optimizely/version.rb

- The "what"; a concise description of each logical change
- Another change
The "why", or other context.
- "THING-1234" or "Fixes #123"

release 3.5.0

---

.travis.yml

This PR hooks Fullstack Prod Suite build to Travis.

ci: add FPS tests stage

---

lib/optimizely.rb
lib/optimizely/audience.rb
lib/optimizely/bucketer.rb
lib/optimizely/decision_service.rb
lib/optimizely/helpers/constants.rb
spec/audience_spec.rb
spec/bucketing_spec.rb
spec/decision_service_spec.rb
spec/project_spec.rb

- This PR modifies log messages to be explicit when it's evaluating an experiment and when it's doing so for a Rollout. 
- Added additional unit test to assert audience logs for rollouts. 
- Existing tests should continue to pass.

fix(logs): Fixing log messages

---

lib/optimizely/config/datafile_project_config.rb
lib/optimizely/optimizely_config.rb
lib/optimizely/project_config.rb
spec/config/datafile_project_config_spec.rb
spec/optimizely_config_spec.rb

Adds datafile string inside project config and optimizely config.
Added unit tests. 
All checks should pass.

feat: Add datafile accessor to config

---

lib/optimizely/semantic_version.rb
spec/semantic_version_spec.rb

This PR adds some additional checks when  figuring out if the given version is a build or a prerelease. 
For a pre-release version . '-' should come before '+' ( if plus exists). 
For a build version: '+' should come before '-' (if minus exists)
Added unit tests
- "THING-1234" or "Fixes #123"

fix: check pre-release and build versions

---

.gitignore
lib/optimizely.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/decision_service.rb
lib/optimizely/event/entity/decision.rb
lib/optimizely/event/entity/impression_event.rb
lib/optimizely/event/event_factory.rb
lib/optimizely/event/user_event_factory.rb
lib/optimizely/project_config.rb
spec/config/datafile_project_config_spec.rb
spec/event/batch_event_processor_spec.rb
spec/event/event_entities_spec.rb
spec/event/event_factory_spec.rb
spec/event/user_event_factory_spec.rb
spec/project_spec.rb
spec/spec_params.rb

- Dispatches event when rollout and send_flag_deciions flag is True
- Dispatches event when variation is nil ( neither feature-test nor rollout) and send_flag_decisions is True
- Adds metadata to impression event. 
- Fixed All Unit tests
- Verified Manually with FSC Flag Decisions Tests

feat: send flag decisions

---

lib/optimizely.rb
spec/project_spec.rb

1. Added "enabled" field to decision metadata structure
2. Setting "enabled" to true for activate() since we check for non nil variation. 
1. Manuall tested thoroughly
2. Fixed existing unit tests

feat: added "enabled" field to decision metadata structure

---

lib/optimizely.rb
lib/optimizely/audience.rb
lib/optimizely/bucketer.rb
lib/optimizely/decision_service.rb
spec/audience_spec.rb
spec/bucketing_spec.rb
spec/decision_service_spec.rb
spec/project_spec.rb

Reasons were previously being collected by sending a reasons object down the stack to all the related functions which would mutate it by pushing their own reasons. This is now changed. Every related function now returns the reasons array along with the actual value.
- Manually tested thoroughly.
- Fixed all the affected unit test.
- FSC passing

refactor: Changed the way reasons are being returned from decide APIs

---

lib/optimizely/config/datafile_project_config.rb
lib/optimizely/optimizely_config.rb
lib/optimizely/project_config.rb
spec/config/datafile_project_config_spec.rb
spec/optimizely_config_spec.rb
spec/spec_params.rb

- Sdk and environment keys are going to be parse in sdk and will be sent back in optimizelyConfig
All unit tests and FSC tests should pass

Feat: added SDKkey and environmentKey in datafile

---

lib/optimizely.rb
lib/optimizely/bucketer.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/decision_service.rb
lib/optimizely/project_config.rb
spec/config/datafile_project_config_spec.rb
spec/decision_service_spec.rb
spec/project_spec.rb

- Fixed an issue related to duplicate experiment_key.
- While trying to get variation from the variation_key_map, it was unable to find because the latest experimentKey was overriding the previous one.
- Run with FSC 
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/jobs/523753247

feat: Duplicate experiment key issue with multi feature flag

---

CHANGELOG.md
lib/optimizely/version.rb
spec/project_spec.rb

prepare for release 3.8.1
All Full stack compatibility tests and unit tests pass.

chore: prepare for release 3.8.1

---

lib/optimizely/condition_tree_evaluator.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/optimizely_config.rb
spec/config/datafile_project_config_spec.rb
spec/optimizely_config_spec.rb
spec/spec_params.rb

The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment
All FSC tests OPTIMIZELY_CONFIG_V2 tests should pass.
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/235036023

feat(OptimizelyConfig): Add new fields to OptimizelyConfig

---

lib/optimizely.rb
lib/optimizely/decision_service.rb
lib/optimizely/optimizely_user_context.rb
spec/optimizely_user_context_spec.rb

- Updated forced-decision API request parameters.
- Added `OptimizelyDecisionContext` and `OptimizelyForcedDecision` structs.
- All existing unit test should pass.
- All FSC cases should pass.

refact(forced-decision): Support for decision context added.

---

lib/optimizely/optimizely_user_context.rb
spec/optimizely_user_context_spec.rb

- Remove config-ready check from forced-decision apis
- Unit and FSC tests

fix(ForcedDecision): remove config-ready check from forced-decision apis

---

lib/optimizely/optimizely_user_context.rb
spec/optimizely_user_context_spec.rb

- `remove_all_forced_decision` renamed to `remove_all_forced_decisions` to sync with other SDKs.
- All unit tests and FSC should pass.
- https://app.travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/242966525

fix: Rename remove_all_forced_decision

---

lib/optimizely.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/decision_service.rb
lib/optimizely/optimizely_user_context.rb
spec/optimizely_user_context_spec.rb

- Crash fixes and order set for variation by flag first then experiment
- All unit tests and FSC should pass

fix: Forced variation not available in experiment

---

lib/optimizely.rb
lib/optimizely/decision_service.rb
lib/optimizely/optimizely_user_context.rb

Summary
-------
- `find_validated_forced_decision` moved to decision service.
Test plan
---------
- All unit tests and FSC should pass.

refactor: moved validated forced decision to decision service.

---

lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/config_manager/static_project_config_manager.rb

`OptimizelyConfig` object is generated when SDK is being initialized. This operation is heavy and blocks the SDK from initializing quickly. This object is only used when users explicitly access it using `get_optimizely_config` API call. This PR moves the creation of this object from SDK initialization to the actual API call.
- Manually tested thoroughly
- All unit tests pass
- All FSC tests pass
fixes #295

enhancement: Generate OptimizelyConfig object on API Call instead of SDK initialization

---

lib/optimizely/event_dispatcher.rb
lib/optimizely/helpers/constants.rb
lib/optimizely/odp/zaius_graphql_api_manager.rb
spec/event_dispatcher_spec.rb
spec/odp/zaius_graphql_api_manager_spec.rb

Provides an internal service for ODP graphQL server access. 
- Supports fetching segments from the ODP server.
Added:
- zaius_graphql_api_manager_spec.rb
[OASIS-8434](https://optimizely.atlassian.net/browse/OASIS-8434)

feat: add ODP GraphQLApi interface

---

lib/optimizely/odp/odp_config.rb
lib/optimizely/odp/odp_segment_manager.rb
lib/optimizely/odp/zaius_graphql_api_manager.rb
spec/odp/odp_segment_manager_spec.rb
spec/odp/zaius_graphql_api_manager_spec.rb

Adds OdpSegmentManager to provide internal services for fetching segments from the ODP server. 
- Provides an internal api for fetching segments with given { api_key, api_host, customer key, customer value, segments subset, and options }.
- Manages a LRU cache for fetched segments (size and timeout are configurable).
- On segment fetch request, looks up the cache for the user key first. On cache hit (or timeout not expired) it returns the cached segments. Otherwise, it sends a fetch request to the ODP server and caches the result.
- Supports options for cache lookup (IGNORE_CACHE, RESET_CACHE).
- Added  odp_segment_manager_spec.rb
[OASIS-8446](https://optimizely.atlassian.net/browse/OASIS-8446)

feat: add odp segment manager

---

lib/optimizely/helpers/constants.rb
lib/optimizely/odp/zaius_rest_api_manager.rb
spec/odp/zaius_rest_api_manager_spec.rb

Provide an internal service for sending ODP events via REST api. 
- When dispatch is completed successfully, no action is required.
- Returns should_retry bool to allow retries on network/server errors
- added zaius_rest_api_manager_spec.rb
[OASIS-8450](https://optimizely.atlassian.net/browse/OASIS-8450)

feat: add rest api manager

---

lib/optimizely/helpers/constants.rb
lib/optimizely/helpers/validator.rb
lib/optimizely/odp/odp_config.rb
lib/optimizely/odp/odp_event.rb
lib/optimizely/odp/odp_event_manager.rb
lib/optimizely/odp/odp_segment_manager.rb
spec/odp/odp_event_manager_spec.rb

Summary
-------
OdpEventManager provides internal services for sending ODP events to the ODP server. 
- adds default values to identifiers and data fields for all events.
- stores requested events if they cannot be sent to the server.
- stored events are dispatched when resources are available.
Test plan
---------
- added odp_event_manager_spec.rb
Ticket
------
[OASIS-8445](https://optimizely.atlassian.net/browse/OASIS-8445)

feat: add odp event manager

---

lib/optimizely/helpers/constants.rb
lib/optimizely/odp/odp_event_manager.rb
lib/optimizely/odp/odp_manager.rb
lib/optimizely/odp/odp_segment_manager.rb
spec/odp/odp_event_manager_spec.rb
spec/odp/odp_manager_spec.rb
spec/odp/odp_segment_manager_spec.rb

Provides all internal services related to the ODP integration:
- OdpSegmentManager
- OdpEventManager
- OdpSegmentsCache
Internal API:
- fetch_qualified_segments
- identify_user
- send_event
- odp_manager_spec.rb
- [OASIS-8454](https://jira.sso.episerver.net/browse/FSSDK-8454)

feat: add odp manager

---

lib/optimizely/optimizely_user_context.rb
spec/optimizely_user_context_spec.rb

Summary
-------
-  Skip sending identify user event to odp when user_context is cloned.
Prevents duplicate identify calls from being made.
Test plan
---------
added test to test_user_context.py
Ticket
------
[FSSDK-8477](https://jira.sso.episerver.net/browse/FSSDK-8477)

fix: skip identify on user_context clone

---

lib/optimizely.rb
lib/optimizely/helpers/sdk_settings.rb
lib/optimizely/odp/odp_event_api_manager.rb
lib/optimizely/odp/odp_event_manager.rb
lib/optimizely/odp/odp_manager.rb
lib/optimizely/odp/odp_segment_api_manager.rb
lib/optimizely/odp/odp_segment_manager.rb
spec/odp/odp_event_api_manager_spec.rb
spec/odp/odp_event_manager_spec.rb
spec/odp/odp_manager_spec.rb
spec/odp/odp_segment_api_manager_spec.rb
spec/odp/odp_segment_manager_spec.rb
spec/project_spec.rb

- Fetch segment and send opd event timeout made configurable through `sdk_settings` option
- All unit tests and FSC should pass.
FSSDK-8692

fix: fetch timeout made configurable

---

lib/optimizely.rb
lib/optimizely/config/datafile_project_config.rb
lib/optimizely/exceptions.rb
lib/optimizely/helpers/http_utils.rb
lib/optimizely/helpers/validator.rb
lib/optimizely/odp/odp_segment_api_manager.rb
lib/optimizely/optimizely_config.rb
spec/project_spec.rb
spec/spec_params.rb

Summary
-------
Fix some issues identified by FSC tests
- extraneous identify calls
- duplicate integration key handling
- http uri scheme error
- send_odp_event data validation
Test plan
---------
- All tests pass
Ticket
------
-  [FSSDK-8624](https://jira.sso.episerver.net/browse/FSSDK-8624)

fix: odp issues identified by fsc

---

lib/optimizely.rb
lib/optimizely/config_manager/http_project_config_manager.rb
lib/optimizely/config_manager/project_config_manager.rb
lib/optimizely/config_manager/static_project_config_manager.rb
lib/optimizely/exceptions.rb
lib/optimizely/notification_center_registry.rb
spec/config_manager/http_project_config_manager_spec.rb
spec/notification_center_registry_spec.rb
spec/notification_center_spec.rb
spec/optimizely_factory_spec.rb
spec/optimizely_user_context_spec.rb
spec/project_spec.rb
spec/spec_params.rb

Summary
-------
Create a private registry of NotificationCenters for internal use.
- Remove dependence on user supplied NotificationCenter.
- Resolve issue of notifications being registered with one NotificationCenter and sent to a different one.
Test plan
---------
added tests to
- notification_center_registry_spec.rb
- project_spec.rb
- http_project_config_manager_spec.rb
- optimizely_factory_spec.rb
Ticket
------
[FSSDK-8775](https://jira.sso.episerver.net/browse/FSSDK-8775)

feat: add notification center registry

---

lib/optimizely.rb
lib/optimizely/helpers/sdk_settings.rb
lib/optimizely/odp/odp_event_manager.rb
lib/optimizely/odp/odp_manager.rb
spec/odp/odp_event_manager_spec.rb
spec/project_spec.rb

Added odp_event_flush_interval to OptimizelySdkSetting to pass into the OdpEventManager. The value in seconds determines when to flush queued ODP events.
Updated:
project_spec.rb
odp_event_manager_spec.rb
- [FSSDK-8803](https://jira.sso.episerver.net/browse/FSSDK-8803)

feat: add odp flush interval to sdk_settings

---

lib/optimizely.rb
lib/optimizely/odp/odp_event_manager.rb
lib/optimizely/optimizely_factory.rb
spec/optimizely_user_context_spec.rb
spec/project_spec.rb
spec/user_condition_evaluator_spec.rb

- Making `BatchEventProcessor` the default event processor to match documentation.
- Fixes [#313](https://github.com/optimizely/ruby-sdk/issues/313)
- All tests should pass
[FSSDK-8939](https://jira.sso.episerver.net/browse/FSSDK-8939)

fix: make batch event processor default

---

README.md
optimizely-sdk.gemspec

- Updates readme and optimizely-sdk.gemspec replacing Full Stack with Feature Experimentation
All tests pass
[FSSDK-8956](https://jira.sso.episerver.net/browse/FSSDK-8956)

[FSSDK-8956] docs: change full stack to feature experimentation

---

lib/optimizely.rb
spec/project_spec.rb

Added blocking call to Project.identify_user, Project.fetch_qualified_segments and Project.send_odp_event to ensure datafile has been downloaded before attempting to make odp requests.
all existing tests should pass

fix: block odp calls on datafile

---

lib/optimizely.rb
lib/optimizely/helpers/constants.rb
lib/optimizely/odp/odp_event.rb
spec/odp/odp_event_manager_spec.rb
spec/project_spec.rb

Summary
-------
Add validation to send_odp_events:
- log error when action == None or ""
- use default when type == None or ""
- fix case and/or "-" for `fs_user_id` identifier key
Test plan
---------
added tests to:
odp_event_manager_spec.rb
project_spec.rb
Ticket
------
[FSSDK-9074](https://jira.sso.episerver.net/browse/FSSDK-9074)

[FSSDK-9074] fix: odp event validation

---

lib/optimizely/config/datafile_project_config.rb
spec/event_builder_spec.rb
spec/notification_center_registry_spec.rb
spec/project_spec.rb

Changed `DatafileProjectConfig.create` to use the provided logger in case of error.
- Existing functionality assumed there was no valid logger. This method is always called after logger has been validated.
- If the user has provided a logger, the expectation is that the logger will be used for all logging.
all tests pass
[FSSDK-7825](https://jira.sso.episerver.net/browse/FSSDK-7825)

[FSSDK-7825] fix errant test logging

---

lib/optimizely/odp/odp_segment_api_manager.rb
spec/odp/odp_segment_api_manager_spec.rb

- Aligned with error code used by ODP
all tests should pass
[FSSDK-9130](https://jira.sso.episerver.net/browse/FSSDK-9130)

[FSSDK-9130] fix: invalid identifier error code

---

.devcontainer/devcontainer.json
.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/ENHANCEMENT.yml
.github/ISSUE_TEMPLATE/FEATURE-REQUEST.md
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/ruby.yml
lib/optimizely/bucketer.rb
spec/audience_spec.rb

- Add GitHub Issue templates
- Add devcontainer config
- Pull in contributor's doc fix from #298
- Review in my personal [forked repo](https://github.com/mikechu-optimizely/ruby-sdk/issues/new/choose)
- No code paths changed; existing unit and e2e tests are expected to pass.
- FSSDK-9555

[FSSDK-9555] GitHub Issue Templates

---

lib/optimizely/config_manager/http_project_config_manager.rb

Add soft warning that polling interval under 30 s is not recommended.
- To synchronize with ter SDKs. Peloton had an issue with setting polling interval too low. So we are adding this soft warning to all SDKs including Ruby.
- See Jira ticket below for more.
Unit tests
- [FSSDK-9509](https://jira.sso.episerver.net/browse/FSSDK-9509)

[FSSDK-9509] Update http_project_config_manager.rb with soft log warning about polling interval < 30s

---

lib/optimizely/config_manager/http_project_config_manager.rb

- Remove the guard restricting the polling config manager from being restarted.
- fixes https://github.com/optimizely/ruby-sdk/issues/237
[FSSDK-9381](https://jira.sso.episerver.net/browse/FSSDK-9381)

[FSSDK-9381] fix: remove config manager stop restriction

---

README.md
lib/optimizely.rb
lib/optimizely/audience.rb
lib/optimizely/event/event_factory.rb
lib/optimizely/event_builder.rb
lib/optimizely/helpers/validator.rb
lib/optimizely/optimizely_factory.rb
spec/audience_spec.rb
spec/condition_tree_evaluator_spec.rb
spec/decision_service_spec.rb
spec/notification_center_registry_spec.rb
spec/optimizely_config_spec.rb
spec/optimizely_user_context_spec.rb
spec/project_spec.rb
spec/user_condition_evaluator_spec.rb

The Optimizely constructor uses positional args and since all of them are optional, it can become unwieldy.
This PR changes the positional args to keyword.
[FSSDK-9382](https://jira.sso.episerver.net/browse/FSSDK-9382)
https://github.com/optimizely/ruby-sdk/issues/243

[FSSDK-9382] switch client init args from positional to keyword

---

README.md
lib/optimizely/event_builder.rb

- Add a warning to the readme about using the ruby sdk in a multi threaded environment.
[FSSDK-9951](https://jira.sso.episerver.net/browse/FSSDK-9951)
[#344](https://github.com/optimizely/ruby-sdk/pull/344)

[FSSDK-9951] add multi thread warning

---

.devcontainer/devcontainer.json
.github/workflows/ruby.yml

- upgrade / add Ruby language version 3.3 to sdk and github workflows buid
- local init tests passing
- PR unit and integration teats
- FSC tests passing
- build pases
- [FSSDK-9461](https://jira.sso.episerver.net/browse/FSSDK-9461)

[FSSDK-9461] Bump Ruby version to 3.3

---

README.md
lib/optimizely.rb
lib/optimizely/decision_service.rb
lib/optimizely/helpers/validator.rb
lib/optimizely/optimizely_factory.rb
lib/optimizely/user_profile_tracker.rb
spec/decision_service_spec.rb
spec/project_spec.rb
spec/user_profile_tracker_spec.rb

Summary
-------
- Currently, decideForKeys loops over the list of flags and calls decide for each, which in turn calls ups. So for decideForKeys, there is two calls per flag to UPS. This PR batches UPS calls when using decideForKeys.
Test plan
---------
- Existing tests are updated to work with the new change. New tests will be added for batching.
Issues
------
-  [FSSDK-10765](https://jira.sso.episerver.net/browse/FSSDK-10765)

[FSSDK-10765] enhancement: Implement UPS request batching for decideForKeys

---

lib/optimizely.rb
lib/optimizely/helpers/validator.rb
spec/optimizely_user_context_spec.rb
spec/project_spec.rb

**Summary**
----------
- Added `experiment_id` and `variation_id` to the decision notification listener payload in the Python SDK.
- Ensured that these IDs are included in all decision notifications sent via the notification center.
- Updated unit tests to validate the presence of `experiment_id` and `variation_id` in the payload.
**Why**
-------
To support data warehouse-native customers who rely on SDK notification listeners to send experiment data to their data warehouse, we need to include `experiment_id` and `variation_id` in the payload. This ensures that the stats engine can correctly compute experiment results based on warehouse data.
**Test Plan**
------------
- Modify existing or add unit tests to check for the presence of `experiment_id` and `variation_id` in the notification …

[FSSDK-11389] update: experiment_id and variation_id added to payloads

---

lib/optimizely/odp/lru_cache.rb
spec/odp/lru_cache_spec.rb

Added remove method in LRU cache class
Added remove method in LRU cache class
[FSSDK-11158](https://jira.sso.episerver.net/browse/FSSDK-11158)

[FSSDK-11158] update: add remove method in LRU Cache for CMAB service

---

.github/workflows/ruby.yml

Running rubocop via Bundler is currently failing due to a version conflict between the tsort gem and Ruby 3.0.0.
The existing unit tests has to pass.
[FSSDK-11723](https://jira.sso.episerver.net/browse/FSSDK-11723)

[FSSDK-11723] fix: rubocop failing on ruby 3.0.0
