optimizely/ruby-sdk

lib/optimizely.rb, lib/optimizely/event_builder.rb, lib/optimizely/project_config.rb, spec/audience_spec.rb, spec/bucketing_spec.rb, spec/condition_spec.rb, spec/event_builder_spec.rb, spec/project_config_spec.rb, spec/project_spec.rb, spec/spec_params.rb
Approved at: https://phabricator.optimizely.com/D12539
@aliabbasrizvi @haleybash-optimizely @mikeng13 @vignesh-optimizely @alda-optimizely @wangjoshuah @jophde
=> Add EventBuilderV2

.gitignore, lib/optimizely.rb, lib/optimizely/helpers/constants.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/project_config.rb, spec/event_builder_spec.rb, spec/project_spec.rb, spec/spec_params.rb
@delikat @aliabbasrizvi @vraja2 @mikeng13
=> Introduce v2 JSON schema validation and `attributes` rather than `dimensions` for v2

.coveralls.yml, .travis.yml, Gemfile, README.md, spec/spec_helper.rb
* Add Travis and Coveralls
* Add badges
=> Restore Travis and Coveralls badges (#18)

optimizely-sdk.gemspec
This updates the gemspec to allow httparty 0.14
=> Allow httparty 0.14

CHANGELOG, LICENSE, lib/optimizely.rb, lib/optimizely/audience.rb, lib/optimizely/bucketer.rb, lib/optimizely/condition.rb, lib/optimizely/error_handler.rb, lib/optimizely/event_builder.rb, lib/optimizely/event_dispatcher.rb, lib/optimizely/exceptions.rb, lib/optimizely/helpers/constants.rb, lib/optimizely/helpers/group.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/logger.rb, lib/optimizely/params.rb, lib/optimizely/project_config.rb, lib/optimizely/version.rb, spec/audience_spec.rb, spec/benchmarking/benchmark.rb, spec/benchmarking/data.rb, spec/bucketing_spec.rb, spec/condition_spec.rb, spec/event_builder_spec.rb, spec/event_dispatcher_spec.rb, spec/project_config_spec.rb, spec/project_spec.rb, spec/spec_helper.rb, spec/spec_params.rb
=> Release v1.0.2

LICENSE, lib/optimizely.rb, lib/optimizely/audience.rb, lib/optimizely/bucketer.rb, lib/optimizely/condition.rb, lib/optimizely/error_handler.rb, lib/optimizely/event_builder.rb, lib/optimizely/event_dispatcher.rb, lib/optimizely/exceptions.rb, lib/optimizely/helpers/constants.rb, lib/optimizely/helpers/group.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/logger.rb, lib/optimizely/params.rb, lib/optimizely/project_config.rb, lib/optimizely/version.rb, spec/audience_spec.rb, spec/benchmarking/benchmark.rb, spec/benchmarking/data.rb, spec/bucketing_spec.rb, spec/condition_spec.rb, spec/event_builder_spec.rb, spec/event_dispatcher_spec.rb, spec/project_config_spec.rb, spec/project_spec.rb, spec/spec_helper.rb, spec/spec_params.rb
=> Fix license dates

CHANGELOG, lib/optimizely.rb, lib/optimizely/event_builder.rb, lib/optimizely/exceptions.rb, lib/optimizely/helpers/event_tag_utils.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/version.rb, spec/event_builder_spec.rb, spec/event_tag_utils_spec.rb, spec/project_spec.rb
* Introduce support for event tags.
* Add optional eventTags argument to track method signature.
* Deprecating optional eventValue argument in track method signature.
=> Release v1.1.0

CHANGELOG, README.md, lib/optimizely/bucketer.rb, lib/optimizely/version.rb, spec/bucketing_spec.rb
=> Gracefully handle empty string entityIDs

lib/optimizely.rb, lib/optimizely/bucketer.rb, lib/optimizely/event_builder.rb, lib/optimizely/project_config.rb, spec/bucketing_spec.rb, spec/event_builder_spec.rb, spec/project_config_spec.rb, spec/project_spec.rb
Don't review, it's just to get coverage report
=> Refactor order of bucketing operations.

CHANGELOG, lib/optimizely/version.rb
=> Prepare for 1.2.0 release

lib/optimizely.rb, lib/optimizely/bucketer.rb, lib/optimizely/decision_service.rb, lib/optimizely/event_builder.rb, spec/bucketing_spec.rb, spec/decision_service_spec.rb, spec/project_spec.rb
=> Add decision service

lib/optimizely.rb, lib/optimizely/decision_service.rb, lib/optimizely/project_config.rb, lib/optimizely/user_profile_service.rb, spec/decision_service_spec.rb
=> Add support for user profiles

lib/optimizely/project_config.rb, spec/project_config_spec.rb, spec/spec_params.rb
=> Parse feature flags

lib/optimizely/project_config.rb, spec/project_config_spec.rb, spec/spec_params.rb
=> Parse rollouts from datafile

lib/optimizely/decision_service.rb, lib/optimizely/project_config.rb, spec/decision_service_spec.rb, spec/project_config_spec.rb, spec/spec_params.rb
=> Rollout bucketing

lib/optimizely.rb, lib/optimizely/helpers/constants.rb, lib/optimizely/helpers/variable_type.rb, lib/optimizely/project_config.rb, spec/decision_service_spec.rb, spec/project_config_spec.rb, spec/project_spec.rb, spec/spec_params.rb, spec/variable_type_helper_spec.rb
=> Feature variable accessors

lib/optimizely/event_builder.rb, lib/optimizely/helpers/event_tag_utils.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/version.rb, spec/event_builder_spec.rb, spec/event_tag_utils_spec.rb, spec/project_spec.rb
✏️ New Payload
✏️ Numeric Event Support
✏️ Event Builder and Event Tags Unit Tests
=> New Event Builder Payload + Numeric Event Support

lib/optimizely.rb, lib/optimizely/event_builder.rb, lib/optimizely/helpers/event_tag_utils.rb, spec/event_builder_spec.rb, spec/event_tag_utils_spec.rb, spec/notification_center_spec.rb
* Revenue value parsed as in https://github.com/optimizely/php-sdk/pull/91
* Added logger to EventBuilder
=> Parse numeric float/string as integer and add logger

lib/optimizely.rb, lib/optimizely/helpers/constants.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/project_config.rb, spec/project_config_spec.rb, spec/project_spec.rb
Implements Null and String validator for inputs.
inputs : ('feature_flag_key', 'experiment_key', 'user_id', 'variation_key', 'variable_key' and 'variable_type')
Methods:
-> Activate 
-> get_variation
-> Track
-> set_forced_variation through project_config-> set_forced_variation
-> get_forced_variation through project_config-> get_forced_variation
-> is_feature_enabled
-> get_enabled_features
-> get_feature_variable_for_type
=> Implements inputs validator

lib/optimizely.rb, spec/project_spec.rb
=> Add datafile isValid check in feature accessor methods

.travis.yml, Gemfile, lib/optimizely/condition.rb, lib/optimizely/decision_service.rb, lib/optimizely/event_builder.rb, lib/optimizely/helpers/validator.rb, lib/optimizely/notification_center.rb, lib/optimizely/project_config.rb, optimizely-sdk.gemspec, spec/spec_helper.rb
Description:
Some small housekeeping.
1. Test against latest minor versions of ruby (excluding 2.6, which is not published)
2. Unpin stuff. This is a general rule (IMO) in the ruby world. You don't pin things unless you have a reason. 
3. Fix small style violations
=> Test against ruby version(s)

.github/pull_request_template.md, CONTRIBUTING.md
**Summary**
- Adds commit message guidelines in CONTRIBUTING.md.
- Adds PR template for Github PRs.
=> chore(contrib): Add PR template and commit message guidelines.

CHANGELOG.md, lib/optimizely/version.rb
=> Updating CHANGELOG and version for 3.0.0 release

CHANGELOG.md, lib/optimizely/project_config.rb, lib/optimizely/version.rb, spec/project_config_spec.rb, spec/spec_params.rb
- Keeping 3.1.x in sync with master so that it's easier to merge later on
=> chore: Merge latest master into 3.1.x

lib/optimizely/config_manager/project_config_manager.rb, lib/optimizely/config_manager/static_project_config_manager.rb, spec/config_manager/static_project_config_manager_spec.rb
- Introduces project config manager, and static project config manager
- Unit tests
=> feat(datafile-management): Introduces static project config manager

.rubocop_todo.yml, lib/optimizely.rb, lib/optimizely/config/datafile_project_config.rb, lib/optimizely/config_manager/async_scheduler.rb, lib/optimizely/config_manager/http_project_config_manager.rb, lib/optimizely/config_manager/static_project_config_manager.rb, lib/optimizely/exceptions.rb, lib/optimizely/helpers/constants.rb, lib/optimizely/notification_center.rb, lib/optimizely/optimizely_factory.rb, spec/config_manager/http_project_config_manager_spec.rb, spec/optimizely_factory_spec.rb, spec/project_spec.rb
- Introduces HTTP Project Config Manager.
- Integrated HTTP Config Manager and Notification Center in Optimizely.
- Introduce generic Async scheduler for executing periodic task in a separate thread.
- Added Config Update Notification.
- Existing and New unit tests should pass.
=> feat(datafile management): Add Polling Manager and Config Update

lib/optimizely/optimizely_factory.rb, spec/optimizely_factory_spec.rb
- Revised Optimizely factory.
- Travis build will pass when PR: https://github.com/optimizely/ruby-sdk/pull/181 is merged!
=> refact: Updates OptimizelyFactory methods.

README.md
Update readme for datafile management
=> docs: update readme for dfm

lib/optimizely/config_manager/http_project_config_manager.rb, spec/config_manager/http_project_config_manager_spec.rb
-  Fixed polling interval type issue.
- Added log messages.
=> Fix: polling interval type bug

README.md
- Lists third parties libraries in README.
- OASIS-4441
=> Refact(README): Adds third party libraries

CHANGELOG.md, lib/optimizely/version.rb
- Updated CHANGELOG.md
- Updated Version
=> chore(release): Preparing for 3.2.0 release

.travis.yml
SDK_BRANCH should be passed to FSC.
=> fix(ci): branch should be passed to FSC

.rubocop_todo.yml, lib/optimizely/event/entity/conversion_event.rb, lib/optimizely/event/entity/decision.rb, lib/optimizely/event/entity/event_context.rb, lib/optimizely/event/entity/impression_event.rb, lib/optimizely/event/entity/snapshot.rb, lib/optimizely/event/entity/snapshot_event.rb, lib/optimizely/event/entity/visitor.rb, lib/optimizely/event/event_factory.rb, lib/optimizely/event/user_event_factory.rb, lib/optimizely/helpers/date_time_utils.rb, spec/event/event_entities_spec.rb, spec/event/event_factory_spec.rb, spec/event/user_event_factory_spec.rb
- Implemented UserEventFactory in `user_event_factory.rb`, decouples ProjectConfig and provides the object to represent impression and conversion event.
- Implemented EventFactory in `event_factory.rb` represents EventBatch after grouping imp/conv objects.
- Created unit tests for `UserEventFactory` in `user_event_factory_spec.rb`
- Created unit tests for `EventFactory` in `event_factory_spec.rb`
- Converted EventBuilder unit tests to EventFactory to make sure, all scenarios are covered to send payload to Server.
- OASIS-5059
=> feat(eventfactory): Event Factory and UserEventFactory

CHANGELOG.md, lib/optimizely/version.rb
- Bump version
- Update the release date
=> chore: Prepare 3.3.0 release.

CHANGELOG.md, lib/optimizely/version.rb
- Bumps version number
- Adds changelog entry
=> chore: Prepare 3.3.1 release.

lib/optimizely/version.rb
=> (chore): bump version in version.rb

CHANGELOG.md
=> (chore): release tomorrow. using 3.3.2

CHANGELOG.md, lib/optimizely/version.rb
- prepare for 3.5.0-beta release
=> chore: prepare for 3.5.0-beta release

.travis.yml
Adds source clear agent to travis run.
=> ci: add srcclr to travis

CHANGELOG.md, lib/optimizely/version.rb
=> chore: prepare for 3.6.0

CHANGELOG.md, lib/optimizely/version.rb
- Releasing flag decisions
- were augmented.
=> chore: updates for release

CHANGELOG.md, lib/optimizely/version.rb, spec/project_spec.rb
=> chore: prepare for release 3.8.0

CHANGELOG.md, lib/optimizely/version.rb, spec/project_spec.rb
=> chore: prepare for 3.9.0 release.

CHANGELOG.md, lib/optimizely/version.rb, spec/optimizely_user_context_spec.rb, spec/project_spec.rb
=> chore: prepare for release 3.10.0

.github/workflows/integration_test.yml, .github/workflows/ruby.yml
- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`
=> feat: updated for fsc git action

CHANGELOG.md, lib/optimizely/version.rb
- Prepare for release 4.0.0
[OASIS-8440](https://optimizely.atlassian.net/browse/OASIS-8440)
=> chore: prepare for release 4.0.0

lib/optimizely/audience.rb
- Fixed segments fetching from audiences.
- All unit tests and FSC tests should pass.
Ticket
------
[FSSDK-8530](https://jira.sso.episerver.net/browse/FSSDK-8530)
=> fix: Fixed audience segment fetch logic

CHANGELOG.md, lib/optimizely/version.rb
- Prepare for  4.0.1 release
[FSSDK-8956](https://jira.sso.episerver.net/browse/FSSDK-8956)
=> [FSSDK-8956] chore: prepare for 4.0.1 release

lib/optimizely/odp/odp_event_manager.rb
- Switch non_block arg from keyword to positional
all tests pass
=> fix: non_block arg

.github/workflows/ruby.yml, .rubocop.yml, README.md, optimizely-sdk.gemspec
- Update json-schema and ruby version
- Outdated Ruby version 2.7. Upgrade to minimum 3.0
-unit, FSC tests passing
https://jira.sso.episerver.net/browse/FSSDK-9033
=> [FSSDK-9033] Update json-schema and ruby version

CHANGELOG.md, LICENSE, lib/optimizely/version.rb
- bump version and update changelog
[FSSDK-8582](https://jira.sso.episerver.net/browse/FSSDK-8582)
=> [FSSDK-8582] chore: prepare for 5.0 release

CHANGELOG.md, lib/optimizely/version.rb
- Updated metadata in gemspec
All unit tests and FSC tests to pass.
- [FSSDK-9990](https://jira.sso.episerver.net/browse/FSSDK-9990)
- https://github.com/optimizely/ruby-sdk/issues/347
=> [FSSDK-9990] Chore: prepare for 5.0.1 minor release

.github/workflows/integration_test.yml
Instead of directly using variables that can contain user input, new intermediate variables were introduced so that script injection attacks could be mitigated. 
- [FSSDK-10665](https://jira.sso.episerver.net/browse/FSSDK-10665)
=> FSSDK-10665] fix: Github Actions YAML files vulnerable to script injections corrected

.github/workflows/ruby.yml
- The "what"; a concise description of each logical change
- Another change
The "why", or other context.
- "THING-1234" or "Fixes #123"
=> chore: check pipeline with ruby 3.0.0

.github/workflows/ruby.yml
Reverts optimizely/ruby-sdk#355
=> Revert "chore: check pipeline with ruby 3.0.0"

CHANGELOG.md, lib/optimizely/event_builder.rb, lib/optimizely/version.rb
Summary
-------
-  Prep for patch release 5.1.0
-  Updated changelog
-  Update version
Issues
------
-  [FSSDK-10847](https://jira.sso.episerver.net/browse/FSSDK-10847)
=> [FSSDK-10847] chore: preparing for release 5.1.0
